/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiba;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Vanessa
 */
public class Doctor extends javax.swing.JFrame {
    
    
    public static String drtext;
    public String url = Tiba.mysqlurl;
    public String pwd = Tiba.mysqlpwd;
            
    LocalTime time =  java.time.LocalTime.now();

    public Doctor() {
        initComponents();
        docid();
        fetchLabData();
        fetchRecpData();
        setDate();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        doctorlabel = new javax.swing.JLabel();
        driDjLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        refreshjButton = new javax.swing.JButton();
        tolabButton = new javax.swing.JButton();
        topharmjButton = new javax.swing.JButton();
        settButton = new javax.swing.JButton();
        fromSETjButton = new javax.swing.JButton();
        exitjButton = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doc_Rec_jTable = new javax.swing.JTable();
        patientIDtxtfield = new javax.swing.JTextField();
        fnameTextField = new javax.swing.JTextField();
        mnamejTextField = new javax.swing.JTextField();
        lnameJTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnosisjTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        testsjTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        prescriptionjTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        symptomsjTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fromLABjTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        labsearchTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pidLabel = new javax.swing.JLabel();
        tidlabel = new javax.swing.JLabel();
        tnamelabel = new javax.swing.JLabel();
        outcomelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("T I B A - H M S ");

        searchTextField.setText("search");
        searchTextField.setCaretColor(new java.awt.Color(0, 102, 102));
        searchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTextFieldMouseClicked(evt);
            }
        });
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        doctorlabel.setText("DOCTOR'S ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 505, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(343, 343, 343))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(doctorlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(driDjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorlabel)
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(driDjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     PATIENTS");

        refreshjButton.setText("REFRESH");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        tolabButton.setText("TO LAB");
        tolabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolabButtonActionPerformed(evt);
            }
        });

        topharmjButton.setText("TO PHARMACY");
        topharmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topharmjButtonActionPerformed(evt);
            }
        });

        settButton.setText("SET");
        settButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settButtonActionPerformed(evt);
            }
        });

        fromSETjButton.setText("SET LAB");
        fromSETjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromSETjButtonActionPerformed(evt);
            }
        });

        exitjButton.setText("EXIT");
        exitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButtonActionPerformed(evt);
            }
        });

        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromSETjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topharmjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tolabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(settButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settButton)
                .addGap(18, 18, 18)
                .addComponent(tolabButton)
                .addGap(18, 18, 18)
                .addComponent(topharmjButton)
                .addGap(18, 18, 18)
                .addComponent(refreshjButton)
                .addGap(80, 80, 80)
                .addComponent(refreshBtn)
                .addGap(18, 18, 18)
                .addComponent(fromSETjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitjButton)
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        doc_Rec_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Middle Name", "Last Name", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doc_Rec_jTable.setGridColor(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(doc_Rec_jTable);

        patientIDtxtfield.setEditable(false);
        patientIDtxtfield.setToolTipText("patient ID");

        fnameTextField.setEditable(false);
        fnameTextField.setToolTipText("first name");

        mnamejTextField.setEditable(false);
        mnamejTextField.setToolTipText("middle name");

        lnameJTextField.setEditable(false);
        lnameJTextField.setToolTipText("last name");

        diagnosisjTextArea.setColumns(20);
        diagnosisjTextArea.setRows(5);
        diagnosisjTextArea.setText("DIAGNOSIS");
        diagnosisjTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diagnosisjTextAreaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(diagnosisjTextArea);

        testsjTextArea.setColumns(20);
        testsjTextArea.setRows(5);
        testsjTextArea.setText("TESTS");
        testsjTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testsjTextAreaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(testsjTextArea);

        prescriptionjTextArea.setColumns(20);
        prescriptionjTextArea.setRows(5);
        prescriptionjTextArea.setText("PRESCRIPTION");
        prescriptionjTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionjTextAreaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(prescriptionjTextArea);

        symptomsjTextArea1.setColumns(20);
        symptomsjTextArea1.setRows(5);
        symptomsjTextArea1.setText("SYMPTOMS\n");
        symptomsjTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                symptomsjTextArea1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(symptomsjTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientIDtxtfield)
                    .addComponent(fnameTextField)
                    .addComponent(mnamejTextField)
                    .addComponent(lnameJTextField)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(patientIDtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("FROM LAB : ");

        fromLABjTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fromLABjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Test ID", "Test Name", "Test Oucome", "Test Cost", "Test Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fromLABjTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(fromLABjTable1);

        jLabel3.setText("PATIENT ID : ");

        labsearchTextField1.setText("search");
        labsearchTextField1.setCaretColor(new java.awt.Color(0, 102, 102));
        labsearchTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labsearchTextField1MouseClicked(evt);
            }
        });
        labsearchTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labsearchTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("TEST ID : ");

        jLabel6.setText("TEST NAME : ");

        jLabel7.setText("OUTCOME : ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labsearchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(pidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67)
                        .addComponent(tidlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(outcomelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(50, 50, 50)
                        .addComponent(tnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labsearchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tidlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(outcomelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextFieldMouseClicked
        // TODO add your handling code here
        searchTextField.setText("");
    }//GEN-LAST:event_searchTextFieldMouseClicked

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
        try {
            
            Connection conn =  DriverManager.getConnection(url, "root", pwd);
            String query = "SELECT patientid, fname, mname, lname FROM recepdocq where patientid=?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, searchTextField.getText());
            ResultSet rs  = pst.executeQuery();
            
            while (rs.next()) {                
                patientIDtxtfield.setText(rs.getString("patientid"));
                fnameTextField.setText(rs.getString("fname"));
                mnamejTextField.setText(rs.getString("mname"));
                lnameJTextField.setText(rs.getString("lname"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void settButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settButtonActionPerformed
        // TODO add your handling code here:
//        new PatientQueue().setVisible(true); 
//        this.dispose();
        for (int i = 0; i < doc_Rec_jTable.getRowCount(); i++) {
            String pid = doc_Rec_jTable.getValueAt(i, 0).toString();
            String fname = doc_Rec_jTable.getValueAt(i, 1).toString();
            String mname = doc_Rec_jTable.getValueAt(i, 2).toString();
            String lname = doc_Rec_jTable.getValueAt(i, 3).toString();
            
            int row =  doc_Rec_jTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)doc_Rec_jTable.getModel();
            String selected = model.getValueAt(row, 0).toString();
            if (row == 0) {
                patientIDtxtfield.setText(pid);
                fnameTextField.setText(fname);
                mnamejTextField.setText(mname);
                lnameJTextField.setText(lname);
            }
        }
    }//GEN-LAST:event_settButtonActionPerformed

    private void tolabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolabButtonActionPerformed
        // TODO add your handling code here:
        String dept = "lab";
        try {
            Connection conn = DriverManager.getConnection(url, "root", pwd);
            String query = "INSERT INTO pharmlab (patientid, fname, mname, lname, doctorid , requests, department, timing)" 
                          + "VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, patientIDtxtfield.getText());
            ps.setString(2, fnameTextField.getText());
            ps.setString(3, mnamejTextField.getText());
            ps.setString(4, lnameJTextField.getText());
            ps.setString(5, driDjLabel.getText());
            ps.setString(6, testsjTextArea.getText());
            ps.setString(7, dept);
            ps.setString(8, time.toString());
                
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "PHARM-LAB QUEUE UPDATED.");
                
        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_tolabButtonActionPerformed

    private void labsearchTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labsearchTextField1MouseClicked
        // TODO add your handling code here:
        labsearchTextField1.setText("");
    }//GEN-LAST:event_labsearchTextField1MouseClicked

    private void labsearchTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labsearchTextField1ActionPerformed
        // TODO add your handling code here:
        try {
            
            Connection conn =  DriverManager.getConnection(url, "root", pwd);
            String query = "SELECT patientid, testid, testname, testoutcome FROM patientresult WHERE patientid=?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, labsearchTextField1.getText());
            pst.executeQuery();
            
            ResultSet rs = null;
            while (rs.next()) {                
                pidLabel.setText(rs.getString("patinetid"));
                tidlabel.setText(rs.getString("testid"));
                tnamelabel.setText(rs.getString("testname"));
                outcomelabel.setText(rs.getString("testoutcome"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_labsearchTextField1ActionPerformed

    private void topharmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topharmjButtonActionPerformed
        // TODO add your handling code here:
        String dept = "pharmacy";
        
        try {
            Connection conn = DriverManager.getConnection(url, "root", pwd);
                    String query = "INSERT INTO pharmlab (patientid, fname, mname, lname, doctorid, requests, department, timing, diagnosis)" 
                          + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement ps = conn.prepareStatement(query);
                    ps.setString(1, patientIDtxtfield.getText());
                    ps.setString(2, fnameTextField.getText());
                    ps.setString(3, mnamejTextField.getText());
                    ps.setString(4, lnameJTextField.getText());
                    ps.setString(5, driDjLabel.getText());
                    ps.setString(6, prescriptionjTextArea.getText());
                    ps.setString(7, dept);
                    ps.setString(8, time.toString());
                    ps.setString(9, diagnosisjTextArea.getText());

                
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "PHARM-LAB QUEUE UPDATED");
                
        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_topharmjButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        // TODO add your handling code here:
        fetchLabData();
        fetchRecpData();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void fromSETjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromSETjButtonActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < fromLABjTable1.getRowCount(); i++) {
            String pid = fromLABjTable1.getValueAt(i, 0).toString();
            String tid = fromLABjTable1.getValueAt(i, 1).toString();
            String tname = fromLABjTable1.getValueAt(i, 2).toString();
            String toutcome = fromLABjTable1.getValueAt(i, 3).toString();
            
            int row =  fromLABjTable1.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)fromLABjTable1.getModel();
            String selected = model.getValueAt(row, 0).toString();
            if (row == 0) {
                pidLabel.setText(pid);
                tidlabel.setText(tid);
                tnamelabel.setText(tname);
                outcomelabel.setText(toutcome);
            }
        }
    }//GEN-LAST:event_fromSETjButtonActionPerformed

    private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_exitjButtonActionPerformed

    private void diagnosisjTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diagnosisjTextAreaMouseClicked
        // TODO add your handling code here:
        diagnosisjTextArea.setText("");
    }//GEN-LAST:event_diagnosisjTextAreaMouseClicked

    private void testsjTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testsjTextAreaMouseClicked
        // TODO add your handling code here:
        testsjTextArea.setText("");
    }//GEN-LAST:event_testsjTextAreaMouseClicked

    private void prescriptionjTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionjTextAreaMouseClicked
        // TODO add your handling code here:
        prescriptionjTextArea.setText("");
    }//GEN-LAST:event_prescriptionjTextAreaMouseClicked

    private void symptomsjTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symptomsjTextArea1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsjTextArea1MouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        fetchLabData();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        drtext = args[0];
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextArea diagnosisjTextArea;
    private javax.swing.JTable doc_Rec_jTable;
    private javax.swing.JLabel doctorlabel;
    private javax.swing.JLabel driDjLabel;
    private javax.swing.JButton exitjButton;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JTable fromLABjTable1;
    private javax.swing.JButton fromSETjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField labsearchTextField1;
    private javax.swing.JTextField lnameJTextField;
    private javax.swing.JTextField mnamejTextField;
    private javax.swing.JLabel outcomelabel;
    private javax.swing.JTextField patientIDtxtfield;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JTextArea prescriptionjTextArea;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton settButton;
    private javax.swing.JTextArea symptomsjTextArea1;
    private javax.swing.JTextArea testsjTextArea;
    private javax.swing.JLabel tidlabel;
    private javax.swing.JLabel tnamelabel;
    private javax.swing.JButton tolabButton;
    private javax.swing.JButton topharmjButton;
    // End of variables declaration//GEN-END:variables

    private void docid() {
        driDjLabel.setText(drtext);
    }
    
    private void setDate() {
//        Date date = new Date(java.time.LocalDate.now());
        LocalDate date =  java.time.LocalDate.now();
        dateLbl.setText(date.toString());
    }
    
    private void fetchLabData() {
        try {
            ResultSet rs = null;
            Connection conn = DriverManager.getConnection(url, "root", pwd);
            String query = "SELECT patientid, testid, testname, testoutcome, testdate FROM patientresult";
            PreparedStatement pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            
            fromLABjTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void fetchRecpData() {
        try {
            ResultSet rs = null;
            Connection conn = DriverManager.getConnection(url, "root", pwd);
            String query = "SELECT * FROM recepdocq";
            PreparedStatement pst = conn.prepareStatement(query);
            
            rs = pst.executeQuery();
            
             doc_Rec_jTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
