/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiba;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Vanessa
 */
public class Medicine extends javax.swing.JFrame {

    public static String text;
    public static String pidtext;
    public static String phamid;
    String url = Tiba.mysqlurl;
    String pwd = Tiba.mysqlpwd;
    
    public Medicine() {
        initComponents();
        
        setDate();
        getRequests();
        fetchPhamQ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        PhamIdlabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addMjButton = new javax.swing.JButton();
        rmMjButton = new javax.swing.JButton();
        completeBtn = new javax.swing.JButton();
        exitjButton = new javax.swing.JButton();
        refreshjButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        medidjTextField1 = new javax.swing.JTextField();
        mednamejTextField2 = new javax.swing.JTextField();
        confirmjRadioButton1 = new javax.swing.JRadioButton();
        missedjRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        unitCostjTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totaOveralllCostText = new javax.swing.JTextField();
        snoTextField = new javax.swing.JTextField();
        expDate = new javax.swing.JTextField();
        manDate1 = new javax.swing.JTextField();
        clearjButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totUnitCostjTextField4 = new javax.swing.JTextField();
        unitsTextFiled = new javax.swing.JTextField();
        confirmjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("T I B A - H M S ");

        searchTextField.setText("search");
        searchTextField.setCaretColor(new java.awt.Color(0, 102, 102));
        searchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTextFieldMouseClicked(evt);
            }
        });
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        dateLbl.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 372, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(343, 343, 343))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PhamIdlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel)
                        .addComponent(PhamIdlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        addMjButton.setText("ADD MEDS");
        addMjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMjButtonActionPerformed(evt);
            }
        });

        rmMjButton.setText("REMOVE MEDS");
        rmMjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmMjButtonActionPerformed(evt);
            }
        });

        completeBtn.setText("COMPLETE");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        exitjButton.setText("EXIT");
        exitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButtonActionPerformed(evt);
            }
        });

        refreshjButton1.setText("REFRESH");
        refreshjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rmMjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(completeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshjButton1)
                .addGap(18, 18, 18)
                .addComponent(addMjButton)
                .addGap(18, 18, 18)
                .addComponent(rmMjButton)
                .addGap(18, 18, 18)
                .addComponent(completeBtn)
                .addGap(18, 18, 18)
                .addComponent(exitjButton)
                .addGap(21, 21, 21))
        );

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 102, 102)));

        infoLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medicine ID", "Medicine Name", "Medicine Cost ", "Serial No", "Manufacure Date", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 102, 102)));

        medidjTextField1.setEditable(false);
        medidjTextField1.setToolTipText("test id");
        medidjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidjTextField1ActionPerformed(evt);
            }
        });

        mednamejTextField2.setEditable(false);
        mednamejTextField2.setToolTipText("test name");

        confirmjRadioButton1.setText("confirm");
        confirmjRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmjRadioButton1MouseClicked(evt);
            }
        });
        confirmjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjRadioButton1ActionPerformed(evt);
            }
        });

        missedjRadioButton2.setText("missed");

        jLabel3.setText("Unit Cost : ");

        unitCostjTextField3.setEditable(false);

        jTextField1.setText("patient id");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Overall Cost : ");

        totaOveralllCostText.setEditable(false);

        snoTextField.setEditable(false);
        snoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snoTextFieldActionPerformed(evt);
            }
        });

        expDate.setEditable(false);
        expDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expDateActionPerformed(evt);
            }
        });

        manDate1.setEditable(false);
        manDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manDate1ActionPerformed(evt);
            }
        });

        clearjButton1.setText("CLEAR");
        clearjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Units : ");

        jLabel6.setText("Total Unit Cost : ");

        totUnitCostjTextField4.setEditable(false);

        confirmjButton.setText("CONFIRM - MED");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(medidjTextField1)
                        .addComponent(mednamejTextField2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(snoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(unitCostjTextField3)
                                .addComponent(totUnitCostjTextField4)
                                .addComponent(unitsTextFiled))))
                    .addComponent(confirmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(confirmjRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(missedjRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(totaOveralllCostText)))
                    .addComponent(clearjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missedjRadioButton2)
                    .addComponent(confirmjRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totaOveralllCostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(clearjButton1)
                .addGap(29, 29, 29))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medidjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mednamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(unitCostjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(totUnitCostjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(unitsTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmjButton))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextFieldMouseClicked
        // TODO add your handling code here
        searchTextField.setText("");
    }//GEN-LAST:event_searchTextFieldMouseClicked

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
        
        try{
            ResultSet resultSet;
            Connection con = DriverManager.getConnection(url, "root", pwd);
            String query = "SELECT medicineid, medname, medcost, serialno, manufacturedate, expirydate FROM medication WHERE medicineid=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, searchTextField.getText());
            resultSet = ps.executeQuery();
            
            while(resultSet.next()){
                medidjTextField1.setText(resultSet.getString("medicineid"));
                mednamejTextField2.setText(resultSet.getString("medname"));
                unitCostjTextField3.setText(resultSet.getString("medcost"));
                snoTextField.setText(resultSet.getString("serialno"));
                manDate1.setText(resultSet.getString("manufacturedate"));
                expDate.setText(resultSet.getString("expirydate"));
            }
            
            getTotalUnitCosts();

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void addMjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMjButtonActionPerformed
        // TODO add your handling code here:
        int r = ThreadLocalRandom.current().nextInt(10000);
        String id = JOptionPane.showInputDialog("MEDICINE ID : ", String.valueOf(r));
        String name = JOptionPane.showInputDialog("MEDICINE NAME : ");
        String cost = JOptionPane.showInputDialog("UNIT COST : ");
        String sno = JOptionPane.showInputDialog("SERIAL NO : ");
        String manu_date = JOptionPane.showInputDialog("MANUFACTURING DATE(yy-mm-dd) : ");
        String exp_date = JOptionPane.showInputDialog("EXPIRY DATE(yy-mm-dd) : ");

        //        System.out.println("id: " + id + "name: " + name + "cost: " + cost);
        try {
            Connection conn = DriverManager.getConnection(url, "root", pwd);
            String query = "INSERT INTO medication (medicineid, medname, medcost, serialno, manufacturedate, expirydate)"
            + "VALUES(?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, id);
            ps.setString(2, name);
            ps.setString(3, cost);
            ps.setString(4, sno);
            ps.setString(5, manu_date);
            ps.setString(6, exp_date);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "NEW MEDICINE RECORD ADDED.");
            
            fetchPhamQ();

        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_addMjButtonActionPerformed

    private void rmMjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmMjButtonActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "Delete medicine record?", "DELETE", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            int row =  jTable1.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

            String selected = model.getValueAt(row, 0).toString();
            if (row == 0) {
                model.removeRow(row);
                try {
                    Connection conn = DriverManager.getConnection(url, "root", pwd);
                    String query = "DELETE FROM medication WHERE medicineid =?";
                    PreparedStatement ps = conn.prepareStatement(query);
                    ps.setString(1, selected);
                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(null, " MEDICINE RECORD DELETED.");
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

        }
    }//GEN-LAST:event_rmMjButtonActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
//        SAVE DATA TO DB, PRINT RECEIPT, 
        JOptionPane.showMessageDialog(null, "generate meds bill");
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            //            String col = jTable1.getValueAt(i, 1).toString();
            String mid = jTable1.getValueAt(i, 0).toString();
            String mname = jTable1.getValueAt(i, 1).toString();
            Boolean checked = Boolean.valueOf(jTable1.getValueAt(i, 2).toString());
            String mcost = jTable1.getValueAt(i, 3).toString();
            String sno = jTable1.getValueAt(i, 4).toString();
            String mftdate = jTable1.getValueAt(i, 5).toString();
            String expdate = jTable1.getValueAt(i, 6).toString();
            String date = jTable1.getValueAt(i, 7).toString();
            ///            String colindex = jTable1.getModel().getValueAt(row, col);
            if (checked) {
                JOptionPane.showMessageDialog(null, "testing if it works " + mid + mname + mcost); //col
                Double totMedsCosts = (Double.parseDouble(mcost));
                JOptionPane.showMessageDialog(null, "to show sum of all meds costs "+totMedsCosts);

                pharmacyBill();
                
                try {
                    Connection conn = DriverManager.getConnection(url, "root", pwd);
                    String query = "INSERT INTO prescription (patientid, medicineid, medname, medcost, serialno, manufacturedate, expirydate, date)"
                    + "VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement ps = conn.prepareStatement(query);
                    ps.setString(1, jTextField1.getText());
                    //                    ps.setString(2, col);
                    ps.setString(2, mid);
                    ps.setString(3, mname);
                    ps.setString(4, mcost);
                    ps.setString(5, sno);
                    ps.setString(6, mftdate);
                    ps.setString(7, expdate);
                    ps.setString(8, dateLbl.getText());

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "PATIENT : " + jTextField1.getText() + ", MEDICATION READY.");
                }catch(SQLException | HeadlessException ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }

    }//GEN-LAST:event_completeBtnActionPerformed

    private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Pharmacy().setVisible(true);
    }//GEN-LAST:event_exitjButtonActionPerformed

    private void confirmjRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmjRadioButton1MouseClicked
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection(url, "root", pwd);
            String query = "INSERT INTO prescription (patientid, medicineid, medname, medcost, serialno,"
                    + "manufacturedate, expirydate, date) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, jTextField1.getText());
            ps.setString(2, medidjTextField1.getText());
            ps.setString(3, mednamejTextField2.getText());
            ps.setString(4, unitCostjTextField3.getText());
            ps.setString(5, snoTextField.getText());
            ps.setString(6, manDate1.getText());
            ps.setString(7, expDate.getText());
            ps.setString(8, dateLbl.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "SAVED");
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_confirmjRadioButton1MouseClicked

    private void confirmjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (confirmjRadioButton1.isSelected()) {
             if(jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirm you've filled in the patient's ID.");
             } else {
                try{
                Connection con = DriverManager.getConnection(url, "root", pwd);
                String query = "INSERT INTO prescription (patientid, medicineid, medname, medcost, serialno,"
                        + "manufacturedate, expirydate, date) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, jTextField1.getText());
                ps.setString(2, medidjTextField1.getText());
                ps.setString(3, mednamejTextField2.getText());
                ps.setString(4, unitCostjTextField3.getText());
                ps.setString(5, snoTextField.getText());
                ps.setString(6, manDate1.getText());
                ps.setString(7, expDate.getText());
                ps.setString(8, dateLbl.getText());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "SAVED");
                } catch(SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        
        }
       
        
    }//GEN-LAST:event_confirmjRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void snoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snoTextFieldActionPerformed

    private void expDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expDateActionPerformed

    private void manDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manDate1ActionPerformed

    private void clearjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButton1ActionPerformed
        // TODO add your handling code here:
        medidjTextField1.setText("");
        mednamejTextField2.setText("");
        jTextField1.setText("patient id");
        unitCostjTextField3.setText("");
        snoTextField.setText("");
        manDate1.setText("");
        expDate.setText("");
        
//        fetchPhamQ();
    }//GEN-LAST:event_clearjButton1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        // TODO add your handling code here:
        int totunitcost, totoverallcost;
        totunitcost = Integer.valueOf((unitCostjTextField3.getText())) * Integer.valueOf(unitsTextFiled.getText());

        if(totaOveralllCostText.getText().isEmpty()) {
            totoverallcost = 0 + (Integer.valueOf(totUnitCostjTextField4.getText()) + Integer.valueOf((unitCostjTextField3.getText())) );
        } else {
            totoverallcost = Integer.valueOf(totaOveralllCostText.getText()) + totunitcost;
        }
        
        totUnitCostjTextField4.setText(String.valueOf(totunitcost));
        totaOveralllCostText.setText(String.valueOf(totoverallcost));
    }//GEN-LAST:event_confirmjButtonActionPerformed

    private void refreshjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButton1ActionPerformed
        // TODO add your handling code here:
        fetchPhamQ();
        
        medidjTextField1.setText("");
        mednamejTextField2.setText("");
        jTextField1.setText("patient ID");
        snoTextField.setText("");
        manDate1.setText("");
        expDate.setText("");
        unitsTextFiled.setText("");
        unitCostjTextField3.setText("");
        totUnitCostjTextField4.setText("");
        
    }//GEN-LAST:event_refreshjButton1ActionPerformed

    private void medidjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medidjTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        phamid = args[0];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhamIdlabel1;
    private javax.swing.JButton addMjButton;
    private javax.swing.JButton clearjButton1;
    private javax.swing.JButton completeBtn;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JRadioButton confirmjRadioButton1;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JButton exitjButton;
    private javax.swing.JTextField expDate;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField manDate1;
    private javax.swing.JTextField medidjTextField1;
    private javax.swing.JTextField mednamejTextField2;
    private javax.swing.JRadioButton missedjRadioButton2;
    private javax.swing.JButton refreshjButton1;
    private javax.swing.JButton rmMjButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField snoTextField;
    private javax.swing.JTextField totUnitCostjTextField4;
    private javax.swing.JTextField totaOveralllCostText;
    private javax.swing.JTextField unitCostjTextField3;
    private javax.swing.JTextField unitsTextFiled;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.time.LocalDate date = LocalDate.now();
        dateLbl.setText(date.toString());
    }

    private void getRequests() {
        infoLabel.setText(phamid);
    }
    
    private void fetchPhamQ() {
        try {
            ResultSet rs = null;
            Connection conn = DriverManager.getConnection(url, "root", pwd);
            String query = "SELECT * FROM medication";
            PreparedStatement pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void pharmacyBill() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            //            String col = jTable1.getValueAt(i, 1).toString();
            String mid = jTable1.getValueAt(i, 0).toString();
//            String mname = jTable1.getValueAt(i, 1).toString();
//            Boolean checked = Boolean.valueOf(jTable1.getValueAt(i, 2).toString());
            String mcost = jTable1.getValueAt(i, 3).toString();
//            String sno = jTable1.getValueAt(i, 4).toString();
//            String mftdate = jTable1.getValueAt(i, 5).toString();
//            String expdate = jTable1.getValueAt(i, 6).toString();
//            String date = jTable1.getValueAt(i, 7).toString();
            try {
                Connection con = DriverManager.getConnection(url, "root", pwd);
                String query = "UPDATE billing SET medicinenid=?, medcost=? WHERE patientid=? OR date=?";
    //            UPDATE billing medicinenid, medcost VALUES ?,? WHERE patientid=? AND date=?
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, mid);
                ps.setString(2, mcost);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "printing receipt...");
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
        }
    }

    private void getTotalUnitCosts() {
        int totCosts =  0;
        String uc = unitCostjTextField3.getText();
        String uCbox = unitsTextFiled.getText();
        totCosts = Integer.valueOf(uc) * Integer.valueOf(uCbox);
        totUnitCostjTextField4.setText(String.valueOf(totCosts));
    }
    
}
